### ISSUE TITLE
PSRule.Rules.CAF version mismatch

### ISSUE THREAD

**Issue by Gordonby** [microsoft/PSRule.Rules.CAF#130]
**Description of the issue**

Specifying the prerelease flag on the CAF rules results in a version error.

**To Reproduce**

Ref: https://github.com/Azure/AKS-Construction/actions/runs/4054300944/workflow

```yml
      - name: PSRule for CAF
        uses: microsoft/ps-rule@v2.7.0
        continue-on-error: true #Setting this whilst PSRule gets bedded in, in this project
        with:
          modules: 'PSRule.Rules.CAF'
          inputPath: "${{ env.ParamFilePath }}"
          prerelease: true
```

**Error output**

```text
Error: The module version '0.4.0-B2208003' for 'PSRule.Rules.CAF' does not match the required version '>=0.3.0'. To continue, first update the module to match the version requirement.
```
